config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'todos#index'

  get "/categories", to: "categories#new"

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  post "/logout", to: "sessions#destroy"

  get "/register", to: "users#new", as: :new_user
  post "/register", to: "users#create", as: :users

  resources :todos
  resources :users, only: [:show, :edit, :update]
  resources :categories, only: [:show, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :todos
  belongs_to :user

  validates :name, presence: :true, uniqueness: true
end

app/models/todo.rb
class Todo < ActiveRecord::Base
  belongs_to :user
  belongs_to :category, optional: true

  validates :title, presence: true
  validates :due_date, presence: true
  validates :description, presence: true

  def title_digest
    if title.length > 10
      title[0..9] + '...'
    else
      title
    end
  end

  def self.due_within_next_24_hours
    where(due_date: Time.now..(Time.now + 24.hours))
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :todos
  has_many :categories

  validates :username, presence: true, uniqueness: true
  validates :password, presence: true, on: :create
  validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_login
    if !logged_in?
      flash[:error] = 'You must be logged in to do that.'
      redirect_to root_path
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_login, only: [:new, :create, :show]
  before_action :correct_user, only: [:show]

  def new
    @category = Category.new
  end

  def create
    @category = current_user.categories.build category_params

    if @category.save
      flash[:notice] = "Now we're bakin'!!"
      redirect_to root_path
    else
      flash.now[:error] = "Ooops..."
      render :new
    end
  end

  def show
    @category = Category.find(params[:id])
    @incomplete_todos = @category.todos.where(completed: false, user_id: current_user.id).order(due_date: :asc)
    @complete_todos = @category.todos.where(completed: true, user_id: current_user.id).order(due_date: :asc)
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

  def correct_user
    if Category.find(params[:id]).user != current_user
      flash[:error] = "You went the wrong way. Authorized employees only."
      redirect_to root_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(username: params[:username])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:notice] = 'You have logged in at the bakery'
      redirect_to root_path
    else
      flash[:error] = 'Something is wrong with your username, password, or baguette'
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :require_login, only: [:show, :new, :create, :edit, :update, :destroy]
  before_action :find_todo, only: [:show, :edit, :update, :destroy]

  def index
    if logged_in?
      @incomplete_todos = Todo.where(completed: false, user_id: current_user.id).order(due_date: :asc)
      @complete_todos = Todo.where(completed: true, user_id: current_user.id).order(due_date: :asc)
    end
  end

  def show
  end

  def new
    @todo = Todo.new
    @categories = Category.where(user_id: current_user.id)
  end

  def create
    # not having @categories here causes the collection_select method to throw an error if no category is selected
    @categories = Category.where(user_id: current_user.id)
    @todo = current_user.todos.build(todo_params)
    if @todo.save
      flash[:notice] = "You are getting baguettes"
      redirect_to todos_path
    else
      render "new"
    end
  end

  def edit
    @categories = Category.where(user_id: current_user.id)
  end

  def update
    if @todo.update(todo_params)
      flash[:notice] = "You added jelly to your baguette"
      redirect_to todos_path
    else
      render "edit"
    end
  end

  def destroy
    if @todo.destroy
      flash[:notice] = "You destroyed your sandwich"
      redirect_to todos_path
    else
      flash[:notice] = "Generic error call Jay to fix."
      redirect_to todos_path
    end
  end

  private

  def todo_params
    params.require(:todo).permit(:title, :description, :due_date, :completed, :user_id, :category_id)
  end

  def find_todo
    @todo = Todo.find_by(id: params[:id], user_id: current_user.id)
    if !@todo
      flash[:error] = "What do you think you're doing -- I saw that."
      redirect_to root_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, only: [:show, :edit, :update]
  before_action :authorized_user, only: [:show, :edit, :update]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:notice] = "You're getting baguettes!!!"
      redirect_to root_path
    else
      flash.now[:error] = 'NO BAGUETTES FOR YOU'
      render :new
    end
  end

  def show
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(user_params)
      flash[:notice] = "nice try you got it"
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def authorized_user
    if params[:id].to_i != current_user.id
      flash[:error] = "You're not allowed to do that!"
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/new.html.erb
<h1>Create a category</h1>

<%= render 'shared/errors', obj: @category %>

<%= form_for @category do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.submit %>
<% end %>

app/views/categories/show.html.erb
<h2>Showing Baguettes for <%= @category.name %></h2>
<ul>
  <% @incomplete_todos.each do |todo| %>
    <li>
      <span><%= link_to todo.title, todo_path(todo, todo: {completed: true}), method: :patch %></span>
      <span><%= todo.due_date %></span>
      <span><%= link_to "show", todo_path(todo) %></span>
      <span><%= link_to "edit", edit_todo_path(todo) %></span>
      <span><%= link_to "delete", todo_path(todo), method: :delete %></span>
    </li>
  <% end %>

  <% @complete_todos.each do |todo| %>
    <li class="completed">
      <span><%= link_to todo.title, todo_path(todo, todo: {completed: false}), method: :patch %></span>
      <span><%= todo.due_date %></span>
      <span><%= link_to "show", todo_path(todo) %></span>
      <span><%= link_to "edit", edit_todo_path(todo) %></span>
      <span><%= link_to "delete", todo_path(todo), method: :delete %></span>
    </li>
  <% end %>
</ul>

<%= link_to 'go back', root_path %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTodo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <ul>
  <% obj.errors.full_messages.each do |message| %>
    <li class="error"><%= message %></li>
  <% end %>
  </ul>
<% end %>

app/views/todos/_form.html.erb
<%= render 'shared/errors', obj: @todo %>

<%= form_for @todo do |f| %>
  <div>
    <%= f.label :title %>
  </div>
  <div>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :description %>
  </div>
  <div>
    <%= f.text_area :description, rows: 5 %>
  </div>
  <div>
    <%= f.label :due_date %>
  </div>
  <div>
    <%= f.date_select :due_date %>
  </div><br>

  <%= f.label :category %>
  <%= f.collection_select(:category_id, @categories, :id, :name, prompt: true) %>

  <%= f.submit %>
<% end %>

app/views/todos/edit.html.erb
<%= render 'form' %>

app/views/todos/index.html.erb
<% if logged_in? %>
  <h1 style="text-align: right">Hello, <%= current_user.username %>!</h1>
  <%= link_to 'Profile', user_path(current_user) %>
  <%= link_to 'Log out', logout_path, method: :post %>
  <ul>
    <% @incomplete_todos.each do |todo| %>
      <li>
        <span><%= link_to todo.title, todo_path(todo, todo: {completed: true}), method: :patch %></span>
        <span><%= todo.due_date %></span>
        <span><%= link_to "show", todo_path(todo) %></span>
        <span><%= link_to "edit", edit_todo_path(todo) %></span>
        <% if todo.category %>
          <span><%= link_to todo.category.name, category_path(todo.category) %></span>
        <% end %>
        <span><%= link_to "delete", todo_path(todo), method: :delete %></span>
      </li>
    <% end %>

    <% @complete_todos.each do |todo| %>
      <li class="completed">
        <span><%= link_to todo.title, todo_path(todo, todo: {completed: false}), method: :patch %></span>
        <span><%= todo.due_date %></span>
        <span><%= link_to "show", todo_path(todo) %></span>
        <span><%= link_to "edit", edit_todo_path(todo) %></span>
        <% if todo.category %>
          <span><%= link_to todo.category.name, category_path(todo.category) %></span>
        <% end %>
        <span><%= link_to "delete", todo_path(todo), method: :delete %></span>
      </li>
    <% end %>
  </ul>
  <div>
    <h1><%= link_to "create todo", new_todo_path %></h1>
    <h2><%= link_to "create category", new_category_path %></h2>
  </div>
<% else %>
  <%= link_to 'Log in', login_path %>
  <%= link_to 'Register', new_user_path %>
<% end %>

app/views/todos/new.html.erb
<%= render 'form' %>

app/views/todos/show.html.erb
<h1><%= @todo.title %></h1>
<h2><%= @todo.description %></h2>
<h3><%= @todo.due_date %></h3>
<h4><%= @todo.category.name %></h4>
<% if @todo.completed %>
  <strong><em>COMPLETED!!!</em></strong>
<% else %>
  <h4>Where is my baguette?!??!</h4>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>

<%= form_for @user do |f| %>
  <%= f.label :username %><br>
  <%= f.text_field :username %><br>

  <%= f.label :email %><br>
  <%= f.email_field :email %><br>

  <%= f.label :password %><br>
  <%= f.password_field :password %><br>

  <%= f.submit @user.new_record? ? 'Register' : 'Update' %>
<% end %>

app/views/users/edit.html.erb
<h2>Edit Profile</h2>

<%= render 'form' %>

app/views/users/new.html.erb
<h2>Register</h2>

<%= render 'form' %>

app/views/users/show.html.erb
<h2>Baguette Profile: <%= current_user.username %></h2>

<ul>
  <li>E-mail:</li>
  <li><%= current_user.email %>
  <li><strong>Password Digest (nom nom nom):</strong></li>
  <li><h3>(<em>shhhhhh</em> For your eyes only, please don't copy, k)</h3></li>
  <li><%= current_user.password_digest %></li>
</ul>

<h3>To make a change, you must change yourself - Michael Scott</h3>
<%= link_to "edit your sandwich", edit_user_path(current_user) %>

<%= link_to "go back", root_path %>